name: 'Throttle'
description: 'Serialize jobs across workflow runs and more with Google Cloud Storage'
author: 'Rob Young'
inputs:
  bucket:
    required: true
    description: 'Name of Google Cloud Storage bucket to use.'
  filename:
    required: false
    description: 'Filename to use as a lock.'
    default: 'lock'
  timeout:
    required: false
    description: 'Timeout before acquiring the lock should fail.'
    default: '10m'

runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
